#!/usr/bin/php
<?php

# Implementação do wget em php
$url  = ''; // URL de destino
$file = ''; // Opcional arquivo de destino

if (!isset($argv[1]) || !isset($argv[2])) {
	echo "Usage: wget [URL] [Filename]\n";
} else {
	$url  = $argv[1];
	$file = $argv[2];

	$content = file_get_contents($url);
	file_put_contents($file, $content);
}


